#!/bin/python3

import math
import os
import random
import re
import sys

def solve(s):
    names = s.split(" ")  # Split the input string into words
    capitalized_name = ' '.join(word.capitalize() for word in names)  # Capitalize 
    return capitalized_name  # Return the capitalized name





if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
